ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER CASO CASCADE;
CREATE USER CASO IDENTIFIED BY A;
GRANT CONNECT, RESOURCE TO CASO;
ALTER USER CASO QUOTA UNLIMITED ON USERS;
CONN CASO/A

-- CREACIÓN DE LA TABLA CUERPO
CREATE TABLE CUERPO (
    ID_CUERPO NUMBER(10) PRIMARY KEY,
    DENOMINACION VARCHAR2(50) NOT NULL
);

-- CREACIÓN DE LA TABLA CUARTEL
CREATE TABLE CUARTEL (
    ID_CUARTEL NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    UBICACION VARCHAR2(50) NOT NULL
);

-- CREACIÓN DE LA TABLA COMPAÑIA
CREATE TABLE COMPANIA (
    ID_COMPANIA NUMBER(10) PRIMARY KEY,
    ACTIVIDAD_PRINCIPAL VARCHAR2(50) NOT NULL
);

-- CREACIÓN DE LA TABLA SERVICIO
CREATE TABLE SERVICIO (
    ID_SERVICIO NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR2(50) NOT NULL
);

-- CREACIÓN DE LA TABLA SOLDADO
CREATE TABLE SOLDADO (
    ID_SOLDADO NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    GRADO VARCHAR2(50) NOT NULL,
    CUERPO_ID NUMBER(10),
    COMPANIA_ID NUMBER(10),
    CUARTEL_ID NUMBER(10)
);

-- CREACIÓN DE LA TABLA SOLDADO_SERVICIO
CREATE TABLE SOLDADO_SERVICIO (
    ID_SOLDADOSERVICIO NUMBER(10) PRIMARY KEY,
    SOLDADO_ID NUMBER(10),
    SERVICIO_ID NUMBER(10),
    FECHA DATE NOT NULL
);

-- CREACIÓN DE LA TABLA CUARTEL_COMPAÑIA
CREATE TABLE CUARTEL_COMPANIA (
    ID_CUARTELCOMPANIA NUMBER(10) PRIMARY KEY,
    CUARTEL_ID NUMBER(10),
    COMPANIA_ID NUMBER(10)
);

-- AGREGAR CLAVE FORÁNEA EN SOLDADO HACIA CUERPO
ALTER TABLE SOLDADO
ADD CONSTRAINT FK_CUERPO FOREIGN KEY (CUERPO_ID)
REFERENCES CUERPO(ID_CUERPO);

-- AGREGAR CLAVE FORÁNEA EN SOLDADO HACIA COMPAÑIA
ALTER TABLE SOLDADO
ADD CONSTRAINT FK_COMPANIA FOREIGN KEY (COMPANIA_ID)
REFERENCES COMPANIA(ID_COMPANIA);

-- AGREGAR CLAVE FORÁNEA EN SOLDADO HACIA CUARTEL
ALTER TABLE SOLDADO
ADD CONSTRAINT FK_CUARTEL FOREIGN KEY (CUARTEL_ID)
REFERENCES CUARTEL(ID_CUARTEL);

-- AGREGAR CLAVE FORÁNEA EN SOLDADO_SERVICIO HACIA SOLDADO
ALTER TABLE SOLDADO_SERVICIO
ADD CONSTRAINT FK_SOLDADO FOREIGN KEY (SOLDADO_ID)
REFERENCES SOLDADO(ID_SOLDADO);

-- AGREGAR CLAVE FORÁNEA EN SOLDADO_SERVICIO HACIA SERVICIO
ALTER TABLE SOLDADO_SERVICIO
ADD CONSTRAINT FK_SERVICIO FOREIGN KEY (SERVICIO_ID)
REFERENCES SERVICIO(ID_SERVICIO);

-- AGREGAR CLAVE FORÁNEA EN CUARTEL_COMPAÑIA HACIA CUARTEL
ALTER TABLE CUARTEL_COMPANIA
ADD CONSTRAINT FK_CUARTEL_ID FOREIGN KEY (CUARTEL_ID)
REFERENCES CUARTEL(ID_CUARTEL);

-- AGREGAR CLAVE FORÁNEA EN CUARTEL_COMPAÑIA HACIA COMPAÑIA
ALTER TABLE CUARTEL_COMPANIA
ADD CONSTRAINT FK_COMPANIA_ID FOREIGN KEY (COMPANIA_ID)
REFERENCES COMPANIA(ID_COMPANIA);
